feat: Info message when LSP is out of date
FuelLabs/sway-vscode-plugin pull request #188
Opened 2024-07-01 22:07 UTC by sdankel

Related https://github.com/FuelLabs/sway/issues/5280

Adds a custom key to the `package.json` indicating the latest version of `forc-lsp` at the time of the plugin's release. If the user's version of `forc-lsp` is older than that, they will see an info message.

![image](https://github.com/FuelLabs/sway-vscode-plugin/assets/47993817/21f7aaa3-8a18-475a-a679-5105e725d5ae)

2024-08-18 02:10 UTC, kayagokalp submitted a review, later dismissed

2024-08-20 23:02 UTC, sdankel commented
@JoshuaBatty What do you think about this? I remember you had some objections.

2024-08-21 00:58 UTC, JoshuaBatty commented
I'm just worried there might be a situation where users are on a stable mainnet version of `forc-lsp` that might be behind the latest bleeding edge release. In this instance they might get this message shown to them every session which might be annoying.

2024-08-22 00:13 UTC, sdankel commented
> I'm just worried there might be a situation where users are on a stable mainnet version of `forc-lsp` that might be behind the latest bleeding edge release. In this instance they might get this message shown to them every session which might be annoying.

That's a fair concern. We would have control over it though, as we manually set the minimum version to not receive the warning in the `latestForcVersion` field in package.json. So, we could set it only update it to the latest mainnet version.

2024-08-22 03:32 UTC, JoshuaBatty commented
> > I'm just worried there might be a situation where users are on a stable mainnet version of `forc-lsp` that might be behind the latest bleeding edge release. In this instance they might get this message shown to them every session which might be annoying.
> 
> That's a fair concern. We would have control over it though, as we manually set the minimum version to not receive the warning in the `latestForcVersion` field in package.json. So, we could set it only update it to the latest mainnet version.

Cool, makes sense. I'm happy for this to merge then.

2024-08-22 03:33 UTC, JoshuaBatty requested changes

2024-08-22 03:33 UTC, JoshuaBatty commented on package.json
> +  "latestForcVersion": "0.60.0",
```suggestion
  "latestForcVersion": "0.63.1",
```

2024-08-22 23:50 UTC, JoshuaBatty approved these changes

2024-08-22 23:50 UTC, merged