Add sidebar with contracts panel
FuelLabs/sway-vscode-plugin pull request #69
Opened 2022-06-26 10:41 UTC by sdankel

Edit: opens the contract file when clicked

<img width="564" alt="image" src="https://user-images.githubusercontent.com/47993817/175810283-caf27936-e46f-4c27-99a0-48f9989d8946.png">

Run: runs `fuel run` on the contract file (reusing code from as https://github.com/FuelLabs/sway-vscode-plugin/pull/52)

<img width="629" alt="image" src="https://user-images.githubusercontent.com/47993817/175810307-3dfe841c-b37a-4361-bc2f-aef96eb2cef4.png">

Icons taken from vscode docs and the play icon made with https://boxy-svg.com/

2022-06-26 23:58 UTC, JoshuaBatty approved these changes
Nice work this is great @sdankel.  Awesome to see a logo in the sidebar where we can start adding in nice UI features. I think this feature in particular will become more useful once we support workspaces.

2022-06-27 18:10 UTC, adlerjohn requested changes
This "runs" contract ABI methods, but those aren't runnable. They can be called with particular parameters, but aren't the genesis of interaction.

Should this functionality not work for scripts instead of contract?

2022-06-27 22:10 UTC, sdankel commented on package.json
> +        "contents": "No node contracts found."
What is the genesis of interaction with a contract if it's not its functions?

I was thinking about adding input text boxes for functions that have parameters. 

I'm assuming that an ABI file is 1:1 with a contract. Is that true?

This view is showing each "contract" as an ABI and listing the functions in the ABI underneath it. It's not taking into account if the function is coming from a sway contract or a script.

Do you have any suggestions on how to make this more useful/correct?

2022-06-27 22:11 UTC, sdankel commented on package.json
> +        "contents": "No node contracts found."
> Should this functionality not work for scripts instead of contract?

In it's current form it does work for script.

2022-06-27 22:56 UTC, adlerjohn commented on package.json
> +        "contents": "No node contracts found."
Interactions with a contract's ABI methods are initiated by scripts running. Scripts run in their entirety, they don't have individual functions that run.

2022-06-27 22:56 UTC, adlerjohn commented on package.json
> +        "contents": "No node contracts found."
Rather than a side panel, what would be better would be something like how Rust can run tests, but on script `main()` functions.

2022-06-27 22:57 UTC, adlerjohn commented on package.json
> +        "contents": "No node contracts found."
See: the `Run test` text-button right under `#[test]`.
![image](https://user-images.githubusercontent.com/3290375/176050424-1616e396-cc03-4997-8af2-b329e98928f5.png)

2022-06-28 00:42 UTC, sdankel commented on package.json
> +        "contents": "No node contracts found."
I updated the code and PR description to add panels for scripts and predicates.

2022-06-28 00:43 UTC, sdankel commented on package.json
> +        "contents": "No node contracts found."
I'm not sure I understand your suggestion - in the screenshot you shared, tests can be run individually. In that example, would the contract functions be the tests?

2022-06-28 00:45 UTC, sdankel commented on package.json
> +        "contents": "No node contracts found."
Let me know what you think of the updated screenshots

2022-06-28 01:36 UTC, adlerjohn reviewed
The contract panel should be removed since contract ABI methods can't be ran directly. They need to be called by a script. Predicates also can't be ran directly since they depend on input parameters to evaluate to `true`.

Scripts _can_ be ran directly, with no input, so I would keep the script panel only. Remove the function name since scripts can only start running from their `main()` function.

This is a good start until we can get a run button directly on top of a script's `main()` function.

2022-06-28 01:36 UTC, adlerjohn commented on package.json
> +        "contents": "No node contracts found."
Left comment https://github.com/FuelLabs/sway-vscode-plugin/pull/69#pullrequestreview-1020976912

2022-06-28 19:40 UTC, adlerjohn submitted a review, later dismissed

2022-07-03 14:35 UTC, adlerjohn approved these changes

2022-07-03 23:25 UTC, JoshuaBatty approved these changes

2022-07-04 18:45 UTC, merged